// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module MUX_S (
In0,In1,GND,Out,Vdd,SelBar );
input  In0;
input  In1;
input  GND;
output  Out;
input  Vdd;
input  SelBar;
wire Vdd;
wire net07;
wire In0;
wire In1;
wire GND;
wire Out;
wire SelBar;

TGATE_S    
 I18  ( .Vdd( Vdd ), .In( In1 ), .SelP( SelBar ), .SelN( net07 ), .GND( GND ), .Out( Out ) );

TGATE_S    
 I17  ( .Vdd( Vdd ), .In( In0 ), .SelP( net07 ), .SelN( SelBar ), .GND( GND ), .Out( Out ) );

INV_S    
 I19  ( .Vdd( Vdd ), .In( SelBar ), .GND( GND ), .Out( net07 ) );

endmodule

